appName: adservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.10.1
containerPort: 9555
containerEnvVars:
  - name: PORT
    value: "9555"

resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi

servicePort: 9555
