appName: currencyservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.10.1
containerPort: 7000
containerEnvVars:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "1"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

servicePort: 7000
