releases:
  - name: adservice
    chart: charts/microservice-helm
    values:
      - values/ad-service-values.yaml

  - name: cartservice
    chart: charts/microservice-helm
    values:
      - values/cart-service-values.yaml

  - name: checkoutservice
    chart: charts/microservice-helm
    values:
      - values/checkout-service-values.yaml

  - name: currencyservice
    chart: charts/microservice-helm
    values:
      - values/currency-service-values.yaml

  - name: emailservice
    chart: charts/microservice-helm
    values:
      - values/email-service-values.yaml

  - name: paymentservice
    chart: charts/microservice-helm
    values:
      - values/payment-service-values.yaml

  - name: productcatalogservice
    chart: charts/microservice-helm
    values:
      - values/productcatalog-service-values.yaml

  - name: recommendationservice
    chart: charts/microservice-helm
    values:
      - values/recommendation-service-values.yaml

  - name: shippingservice
    chart: charts/microservice-helm
    values:
      - values/shipping-service-values.yaml

  - name: frontendservice
    chart: charts/frontend
    values:
      - values/frontend-service-values.yaml

  - name: redis-cart
    chart: charts/redis
    values:
      - values/redis-values.yaml
      - appReplicas: 1
      - volumeName: "redis-cart-data"
