apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  #namespace: monitoring
  # labels for prometheus selector
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
    - name: main.rules
      rules:
        - alert: HostHighCpuLoad
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 50
          for: 1m
          labels:
            severity: warning
            namespace: monitoring
          annotations:
            description: "CPU on host is over 50%\n Value = {{ $value }}\n Instance = {{ $labels.instance }}\n"
            summary: "Host CPU load high!"

        - alert: KubernetesPodCrashLooping
          expr: kube_pod_container_status_restarts_total > 2
          for: 0m
          labels:
            severity: critical
            namespace: monitoring
          annotations:
            description: "Pod {{ $labels.pod }} is crash looping\n Value = {{ $value }}"
            summary: "Kubernetes pod crash looping!"
