apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  route:
    receiver: "email"
    repeatInterval: 30m
    routes:
      - matchers:
          - name: alertname
            value: HostHighCpuLoad
      - matchers:
          - name: alertname
            value: KubernetesPodCrashLooping
        repeatInterval: 10m
  receivers:
    - name: "email"
      emailConfigs:
        - to: "datzlatannn@gmail.com"
          from: "datzlatannn@gmail.com"
          smarthost: "smtp.gmail.com:587"
          authUsername: "datzlatannn@gmail.com"
          authIdentity: "datzlatannn@gmail.com"
          authPassword:
            name: gmail-auth
            key: password
